name: Go checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Get Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Run Staticcheck
        run: |
          staticcheck -f stylish ./...
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
